version: "3.3"
services:
  ontotext:
      image: ontotext/graphdb:10.6.4
      volumes:
      - ./graphdb-data:/opt/graphdb/home
      ports:
        - 7200:7200


  rudik:

    build:
      context: ./rudik
    command: ["tail", "-f", "/dev/null"]
