# ubuntu/Dockerfile
FROM ubuntu:latest

RUN apt update && apt install -y wget python3-pip git build-essential cmake

# Additional packages as needed
# Example:
# RUN apt install -y some-other-package

# No default CMD, allowing manual commands or script executions later
